cd pr2_resources_management && git pull && cd ..
cd exp_director_task && git pull && cd ..
cd knowledge_sharing_planner_msgs && git pull && cd ..
cd knowledge_sharing_planner && git pull && cd ..
cd resource_management && git pull && cd ..
cd ontologenius && git pull && cd ..
cd mementar && git pull && cd ..
cd ar_track_alvar && git pull && cd ..
cd uwds3 && git pull && cd ..
cd uwds3_msgs && git pull && cd ..
cd ld_rjs && git pull && cd ..
cd rjs && git pull && cd ..
cd HATPEHDA && git pull && cd ..
cd pr2_mtc && git pull && cd ..
cd moveit && git pull && cd ..